# -*- coding: utf-8 -*-
"""AI-Powered Resume Screening and Ranking System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQDRf9q5Y5MXU_wGcdsx9H7EcdRFDU07
"""

# Install required libraries
#!pip install PyPDF2 scikit-learn numpy

# Import libraries
import PyPDF2
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files

# Define the job description keywords
job_description_keywords = [
    "python", "machine learning", "data analysis", "deep learning",
    "artificial intelligence", "nlp", "pandas", "numpy", "scikit-learn",
    "tensorflow", "keras", "flask", "django", "sql", "git"
]

# Function to extract text from a PDF file
def extract_text_from_pdf(pdf_path):
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        text = ""
        for page in reader.pages:
            text += page.extract_text()
    return text

# Function to calculate the resume score based on keyword matching
def calculate_resume_score(resume_text, keywords):
    # Create a CountVectorizer to convert text to a matrix of token counts
    vectorizer = CountVectorizer().fit([resume_text] + keywords)

    # Transform the resume text and keywords into vectors
    resume_vector = vectorizer.transform([resume_text])
    keyword_vector = vectorizer.transform(keywords)

    # Calculate cosine similarity between the resume and keywords
    similarity_scores = cosine_similarity(resume_vector, keyword_vector)

    # Calculate the average similarity score
    average_score = np.mean(similarity_scores)

    # Normalize the score to a range of 0 to 100
    resume_score = min(max(average_score * 100, 0), 100)

    return resume_score

# Main function to handle resume upload and scoring
def main():
    # Upload the resume PDF file
    print("Please upload your resume (PDF file):")
    uploaded = files.upload()

    # Get the file name of the uploaded PDF
    pdf_name = next(iter(uploaded))

    # Extract text from the PDF
    resume_text = extract_text_from_pdf(pdf_name)

    # Calculate the resume score
    resume_score = calculate_resume_score(resume_text, job_description_keywords)

    # Display the resume score
    print(f"Your Resume Score: {resume_score:.2f}%")

# Run the main function
if __name__ == "__main__":
    main()